###
# This is the place to override the opsworks_commons cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "opsworks_commons/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###
