###
# This is the place to override the mod_php5_apache2 cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "mod_php5_apache2/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the mod_php5_apache2 packages:
#
#normal[:mod_php5_apache2][:packages] = [ 'php-xml',
#                                         'php-common',
#                                         'php-xmlrpc',
#                                         'php-devel',
#                                         'php-gd',
#                                         'php-cli',
#                                         'php-pear-Auth-SASL',
#                                         'php-mysql',
#                                         'php-mcrypt' ]

normal[:mod_php5_apache2][:packages] = [
    "php-xml",
    "php-common",
    "php-xmlrpc",
    "php-devel",
    "php-gd",
    "php-cli",
    "php-pear-Auth-SASL",
    "php-mcrypt",
    "php-pecl-memcached",
    "php-pear",
    "php-pear-XML-Parser",
    "php-pear-DB",
    "php-pear-HTML-Common",
    "php",
    "php-devel",
    "php-pear-Mail",
    "php-pear-Mail-Mime"
  ]