###
# This is the place to override the memcached cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "memcached/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the memcached max connections:
#
#normal[:memcached][:max_connections] = "8192"
