###
# This is the place to override the opsworks_ganglia cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "opsworks_ganglia/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the Ganglia user
#
#normal[:ganglia][:user] = 'cacti'
