###
# This is the place to override the opsworks_agent_monit cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "opsworks_agent_monit/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###
