###
# This is the place to override the opsworks_custom_cookbooks cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "opsworks_custom_cookbooks/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to disable submodules for your site-cookbooks:
#
#normal[:opsworks_custom_cookbooks][:enable_submodules] = false
