###
# This is the place to override the passenger_apache2 cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "passenger_apache2/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the Passenger pool size and lower the idle time:
#
#normal[:passenger][:pool_idle_time] = 3600
#normal[:passenger][:max_pool_size] = 16
