###
# This is the place to override the opsworks_opsworks_postgresql cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "opsworks_postgresql/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the postgres package names
#
#normal[:opsworks_postgresql][:client_package] = "postgresql93"
#normal[:opsworks_postgresql][:devel_package] = "postgresql93-devel"

