###
# This is the place to override the opsworks_rubygems cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "opsworks_rubygems/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the Rubygems version:
#
#normal['opsworks_rubygems']['version'] = '2.1.7'
