###
# This is the place to override the ruby_enterprise cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "ruby_enterprise/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###
