#!/bin/bash

if [ ! -h /var/www/solr-5.0.0 ]; then
  rm -rf /var/www/solr-5.0.0
fi

cd /tmp && curl -O 'http://mirror.nbtelecom.com.br/apache/lucene/solr/5.0.0/solr-5.0.0.tgz'

tar zxvf /tmp/solr-5.0.0.tgz -C /var/www/
if [ ! -h /opt/solr ]; then
  ln -s  /var/www/solr-5.0.0 /var/www/solr
fi

mv /var/www/solr/server/solr  /var/www/solr/server/solr-default

chown -R deploy. /opt/solr-5.0.0 
