###
# This is the place to override the nginx cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "nginx/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to disable NGinx compression:
#
#normal[:nginx][:gzip] = 'off'
#normal[:nginx][:gzip_static] = 'off'

normal[:nginx][:gzip_types] = ["application/x-javascript",
                                "application/xhtml+xml",
                                "application/xml",
                                "application/xml+rss",
                                "application/json",
                                "text/json",
                                "text/css",
                                "text/javascript",
                                "text/plain",
                                "text/xml"]
