###
# This is the place to override the nginx cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "nginx/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to disable NGinx compression:
#
#normal[:nginx][:gzip] = 'off'
#normal[:nginx][:gzip_static] = 'off'

# The following allows specification of the ssl_protocols
# The default ssl_protocols will be used if not set.
# See: http://nginx.org/en/docs/http/configuring_https_servers.html
#normal[:nginx][:ssl_protocols] = 'TLSv1 TLSv1.1 TLSv1.2'

# The following allows ssl to be enforced by all connections by
# redirecting all trafic coming to port 80 to port 443
#normal[:nginx][:force_ssl] = true