###
# This is the place to override the ebs cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "ebs/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the mdadm chunk size:
#
#normal[:ebs][:mdadm_chunk_size] = '512'
