name              'deploy_wrapper'
maintainer        'Cameron Johnston'
maintainer_email  'cameron@rootdown.net'
description       'Provides a definition that sets up an ssh key and ssh wrapper script for use with deploy or deploy_revision resources'
version           '0.2.1'
