###
# This is the place to override the packages cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "packages/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###
