###
# This is the place to override the agent_version cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "agent_version/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###
