###
# This is the place to override the opsworks_cleanup cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "opsworks_cleanup/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the number of log files kept:
#
#normal[:opsworks_cleanup][:keep_logs] = 5
