name             'solr'
maintainer       'David Radcliffe'
maintainer_email 'radcliffe.david@gmail.com'
license          'MIT'
description      'Installs the solr search engine.'
long_description 'See README.md'
version          '0.4.0'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'

depends 'apt'
depends 'java'
