###
# This is the place to override the test_suite cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "test_suite/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###
