###
# This is the place to override the opsworks_bundler cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "opsworks_bundler/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the bundler version:
#
#normal[:opsworks_bundler][:version] = '1.3.5'
