###
# This is the place to override the ssh_users cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "ssh_users/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###
